### ISSUE TITLE
Error: command 'b3ddev.startBlender' not

### ISSUE THREAD

**Issue by gerroon** [JacquesLucke/blender_vscode#3]
Hi

I am tryingto use this extension on Windows 10 x64 and this is an error I get when I try to  start blender inside Vscode. I set the path for Blender exe

The addon is installed and enabled

`Blender Development
jacqueslucke.blender-development
Jacques Lucke
Tools to simplify Blender development.
Disable
Uninstall
Details
Contributions
Dependencies
`

`
Error: command 'b3ddev.startBlender' not found
    at t._tryExecuteCommand (workbench.main.js:3041)
    at workbench.main.js:3041
    at <anonymous>
t.onDidNotificationChange @ workbench.main.js:2429
(anonymous) @ workbench.main.js:2429
e.fire @ workbench.main.js:183
t.notify @ workbench.main.js:2484
t.error @ workbench.main.js:3530
t.onError @ workbench.main.js:3027
(anonymous) @ workbench.main.js:3027
Promise rejected (async)
(anonymous) @ workbench.main.js:3027
setTimeout (async)
t.runAction @ workbench.main.js:3026
t.run @ workbench.main.js:3026
e.run @ workbench.main.js:983
t.elementSelected @ workbench.main.js:1046
(anonymous) @ workbench.main.js:1040
`

thanks

**Comment by JacquesLucke** [comment]
Hey, thank you for the report. I changed a lot of things after I first published this extension. Maybe this is fixed already. Unfortunately I can't publish it in the state it is right now.
I'll let you know when you can try the new version. Until then, you can't really use the extension, sorry.

**Comment by gerroon** [comment]
thanks, looking for it

**Comment by JacquesLucke** [comment]
I just published a new version of the extension in vs code. Please give it a try again. Hope it works...

**Comment by gerroon** [comment]
Thanks, I will give it a go

**Comment by gerroon** [comment]
On top of it, I tried the 2.8 path and this is what I get 



> Executing task in folder _test_addon: C:\BLENDER_28\blender.exe --python C:\DRIVE\APPS\VSCODE\.vscode-oss\extensions\jacqueslucke.blender-development-0.0.8\pythonFiles\launch.py <

Read prefs: C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
found bundled python: C:\BLENDER_28\2.80\python
Collecting pip
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000017A32B79A90>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions')': /simple/pip/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000017A33F320B8>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions')': /simple/pip/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000017A33F32B38>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions')': /simple/pip/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000017A33F03438>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions')': /simple/pip/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000017A33F03160>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions')': /simple/pip/
  Could not find a version that satisfies the requirement pip (from versions: )
No matching distribution found for pip
C:\BLENDER_28\2.80\python\bin\python.EXE: No module named pip
C:\BLENDER_28\2.80\python\bin\python.EXE: No module named pip
Traceback (most recent call last):
  File "C:\DRIVE\APPS\VSCODE\.vscode-oss\extensions\jacqueslucke.blender-development-0.0.8\pythonFiles\launch.py", line 16, in <module>
    allow_modify_external_python=os.environ['ALLOW_MODIFY_EXTERNAL_PYTHON'] == "yes",
  File "C:\DRIVE\APPS\VSCODE\.vscode-oss\extensions\jacqueslucke.blender-development-0.0.8\pythonFiles\include\blender_vscode\__init__.py", line 11, in startup
    allow_modify_external_python)
  File "C:\DRIVE\APPS\VSCODE\.vscode-oss\extensions\jacqueslucke.blender-development-0.0.8\pythonFiles\include\blender_vscode\installation.py", line 16, in ensure_packages_are_installed
    install_packages(package_names)
  File "C:\DRIVE\APPS\VSCODE\.vscode-oss\extensions\jacqueslucke.blender-development-0.0.8\pythonFiles\include\blender_vscode\installation.py", line 29, in install_packages
    assert packages_are_installed(package_names)
AssertionError
Saved session recovery to 'C:\tmp\quit.blend'
Error: Not freed memory blocks: 1, total unfreed memory 0.000084 MB

Terminal will be reused by tasks, press any key to close it.

**Comment by JacquesLucke** [comment]
please read the readme, otherwise.

Yes, you can install those packages yourself.

And yes, I need to provide a better error message in case when there is no internet connection.

**Comment by gerroon** [comment]
Thanks for your time.

I already installed those required pips in my systemwide python, and I am still getting 

```
 Could not find a version that satisfies the requirement pip (from versions: )
No matching distribution found for pip
C:\BLENDER_28\2.80\python\bin\python.EXE: No module named pip
C:\BLENDER_28\2.80\python\bin\python.EXE: No module named pip
Traceback (most recent call last):
```

So I am not sure if I am supposed to install those pips in Blender Python distribution or not, if so how I would do it? Just replace the python37 folder into the  Blender's python?

**Comment by JacquesLucke** [comment]
Thanks!

Let me know how it goes so that I can insert the gained knowledge into the readme and error messages.

**Comment by gerroon** [comment]
Hi

So I believe that I got all the pip stuff and Python versions (I symlinked the system version to Blender/2.80/python 

I can start that version of Blender28 no problem, however I cant seem to be able to start Blender from Vscode using your plugin, I also set a new addon with it. 

This is the only message I have from the terminal



 Executing task in folder _test_addon: C:\BLENDER_28\blender.exe --python T:\APP_SETTINGS\VSCODE\.vscode-oss\extensions\jacqueslucke.blender-development-0.0.8\pythonFiles\launch.py <

The terminal process terminated with exit code: 2

Terminal will be reused by tasks, press any key to close it.


here is the settings

```
 "blender.executables": [
        {
            "path": "C:\\BLENDER_28\\blender.exe",
            "name": "Blender28",
            "isDebug": false
        }
    ],
}

```

**Comment by gerroon** [comment]
Never mind, It was trying to run an addon that was missing the files!. Sorry for the false flag here. However I will keep reporting my experience

**Comment by JacquesLucke** [comment]
It is still weird that Blender crashes when some addon file is missing. 

Anyway, will close this for now. Please open a new issue for, well, new issues.
